apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec:
  targetNamespaces:
  - openshift-operators-redhat
