bases:
- ../base
patchesJson6902:
  - target:
      version: v1
      group: logging.openshift.io
      kind: ClusterLogging
      namespace: openshift-logging
      name: instance
    path: clo-instance.yaml
